# Linear Computation

Here weight matrix is calculated as BA+


In [20]:
import numpy as np

Function which calulates weights by linear computation 

In [21]:
def linear(A,B):
    weights1 = np.matmul(B,np.linalg.pinv(A))
    length = B.shape[1]
    error = (1/length)*np.trace(np.matmul( np.matmul(B, (np.identity(length) - np.matmul(np.linalg.pinv(A), A))), np.transpose(B)))
    print("Computed_error = " ,error)
    
    return weights1

In [22]:
A = np.array([[0,0],[0,1],[1,0],[1,1]]).T
B = np.array([[0],[1],[0],[1]]).T

weights1 = linear(A,B)

print(np.matmul(weights1, A))

Computed_error =  2.7755575615628914e-17
[[ 0.00000000e+00  1.00000000e+00 -1.66533454e-16  1.00000000e+00]]


# Hebbian Learning

Here weights are computed by using B*(A).Transpose

Function which calculates weights by hebbian learning

In [23]:
def Hebbian(C,D):
    weights2 = np.matmul(D,np.transpose(C))
    return weights2

In [24]:
C = np.array([[0,0],[0,1],[1,0],[1,1]]).T
D = np.array([[0],[1],[0],[1]]).T

weights2 = Hebbian(C,D)

print(np.matmul(weights2, C))

[[0 2 1 3]]


# Widrow's Learning  

Here weights are computed by BA+

Function which computes weights by Windrow's Learning

In [42]:
def Widrow(E,F,epochs ,lr):
    weights3 = np.zeros((F[0].shape[0],E[0].shape[0]))
    for i in range (epochs):
        for j in range (len(E)):
            delta = F[j] - np.matmul(weights3,E[j].T)
            weights3 = weights3 + lr * np.matmul(delta, E[j].reshape((1,2)))
    return weights3

In [43]:
E = np.array([[0,0],[0,1],[1,0],[1,1]])
F = np.array([[0],[1],[0],[1]])

weights3 = Widrow(E, F, 10, 0.1)    

print(np.matmul(weights3, np.transpose(E)))

[[0.         0.80694125 0.15561969 0.96256094]]


# Perceptron Learning Law

Function which generates Non-linearity (unit step function)

In [27]:
def unit_function(inputs):
    if (inputs <= 0):
        return 0
    else:
        return 1

In [33]:
def Perceptron(Input,ouput,lr = 0.1):
    weights4 = np.array([1,0,0])
    counter = 0
    while counter !=4:
        counter =0
        for i in range (0,len(Input)):
            outputs = output[i]
            
            temp = np.matmul(np.transpose(weights4),Input[i])
            expected_output = unit_function(temp)
            
            if(expected_output == outputs):
                counter += 1
            
            weights4 = weights4 -lr* (expected_output-outputs)*Input[i]
            weights4[0] = 1
        print(weights4)

In [37]:
Input = np.array([[-1, 0, 0], [-1, 0, 1], [-1, 1, 0], [-1, 1, 1]])

output = np.array([0,1,0,1])

Perceptron(Input,output,lr = 0.1)

[1.  0.1 0.2]
[1.  0.2 0.4]
[1.  0.3 0.6]
[1.  0.4 0.8]
[1.  0.4 0.9]
[1.  0.4 1. ]
[1.  0.4 1.1]
[1.  0.4 1.1]
